<div>

    <h1>Administrador</h1>


    <form enctype="multipart/form-data" action="<?php echo $this->url(array("controller" => "Administrador", "action" => "index")); ?>" method="POST">
        <input type="hidden" name="MAX_FILE_SIZE" value="100000" />
        Choose a file to upload: <input name="uploadedfile" type="file" />
        <br />
        <input type="submit" value="Upload File" />
    </form>

    <?php
    if (isset($this->alumnes)) {
    
        foreach ($this->alumnes as $a){
            
            foreach($a as $aa){
                  echo $aa . " - ";
            }
            
            echo "<br>";
          
        }
        
    }
    ?>

</div>