<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

<?php echo $this->headLink()->appendStylesheet($this->baseUrl() . '/bootstrap/css/bootstrap.min.css'); ?>
<?php echo $this->headLink()->appendStylesheet($this->baseUrl() . '/font-awesome-4.6.3/css/font-awesome.min.css'); ?>

<script type="text/javascript" src="http://code.jquery.com/jquery-1.7.1.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>

<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/datetimepicker-master/jquery.datetimepicker.css" >
<script src="<?php echo $this->baseUrl(); ?>/datetimepicker-master/build/jquery.datetimepicker.full.min.js"></script>

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.2/css/bootstrap-select.min.css">
<!-- Latest compiled and minified JavaScript -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.2/js/bootstrap-select.min.js"></script>

<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <?php
            $sessions = new Zend_Session_Namespace('expireAll');
            ?>
            <a class="navbar-brand" href="#"><span class="glyphicon glyphicon-user"></span><?php echo "  ".$sessions->usuari; ?></a>
        </div>
        <ul class="nav navbar-nav">
            <?php if($sessions->usuari != "Admin") {?>
            <li class=""><a href="<?php echo $this->url(array("controller" => "Festa", "action" => "index")); ?>">FESTES</a></li>
            <?php } ?>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li><a href="<?php echo $this->url(array("controller" => "Login", "action" => "index")); ?>"><span class="glyphicon glyphicon-log-out"></span> Sortir</a></li>
        </ul>
    </div>
</nav>

<?php echo $this->layout()->content; ?>

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="<?php echo $this->baseUrl(); ?>/bootstrap/js/bootstrap.min.js"></script>
