
<?php echo $this->headLink()->appendStylesheet($this->baseUrl().'/bootstrap/css/bootstrap.min.css'); ?>
<?php echo $this->headLink()->appendStylesheet($this->baseUrl().'/font-awesome-4.6.3/css/font-awesome.min.css'); ?>

<script type="text/javascript" src="http://code.jquery.com/jquery-1.7.1.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="parallax.js-1.4.2/parallax.js"></script>

<?php echo $this->layout()->content; ?>