
<?php echo $this->headLink()->appendStylesheet($this->baseUrl() . '/bootstrap/css/bootstrap.min.css'); ?>
<?php echo $this->headLink()->appendStylesheet($this->baseUrl() . '/font-awesome-4.6.3/css/font-awesome.min.css'); ?>

<script type="text/javascript" src="http://code.jquery.com/jquery-1.7.1.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="parallax.js-1.4.2/parallax.js"></script>

<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="#"><span class="glyphicon glyphicon-user"></span><?php echo " ".$this->layout()->usuari; ?></a>
        </div>
        <ul class="nav navbar-nav">
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li><a href="<?php echo $this->url(array("controller" => "Login", "action" => "index")); ?>"><span class="glyphicon glyphicon-log-out"></span> Sortir</a></li>
        </ul>
    </div>
</nav>

<?php echo $this->layout()->content; ?>