<style>

    th, td {
        text-align: center;
    }

</style>
<div class="container">

    <div class="row">

        <div class="col-xs-12">

            <h1>Festes organitzades</h1>

            <table class="table table-bordered table-striped table-hover">

                <tr>
                    <th>Lloc</th>
                    <th>Data</th>
                    <th>Organitzadors</th>
                    <th> --- </th>
                </tr>

                <?php
                foreach ($this->festesOrganitzador as $festa) {

                    echo "<tr>";
                    echo "<td>" . $festa[0]['lloc'] . "</td><td>" . $festa[0]['data'] . "</td>";
                    echo "<td>";
                    foreach ($festa[1] as $o) {
                        echo $o->id_organitzador . ", ";
                    }
                    echo "</td>";
                    ?>
                    <td><a href='<?php echo $this->url(array("controller" => "Festa", "action" => "llistarparticipants", "idFesta" => $festa[0]['id'])); ?>'>Participants</a></td>
                    <?php
                    echo "</tr>";
                }
                ?>

            </table>

            <a href="<?php echo $this->url(array("controller" => "Festa", "action" => "crearfesta")); ?>" class="btn btn-success col-xs-12">Crear festa </a>

        </div>

        <div class="col-xs-12">

            <h1>Festes Participant</h1>

            <table class="table table-bordered table-striped table-hover">

                <tr>
                    <th>Lloc</th>
                    <th>Data</th>
                    <th>Organitzadors</th>
                    <th> --- </th>
                    <th> --- </th>
                </tr>

                <?php
                foreach ($this->festesParticipant as $festa) {
                    ?>
                    <tr>
                        <td><?php echo $festa['lloc']; ?></td>
                        <td><?php echo $festa['data']; ?></td>
                        <td><?php ?></td>
                        <?php if ($festa['acceptat']) { ?>
                            <td><i class="fa fa-check" aria-hidden="true" style="color: green"></i></td>
                            <td><a href="<?php echo $this->url(array("controller" => "Festa", "action" => "acceptar", "id" => $festa['id'], "estat" => "0")); ?>">Anular inivitacio</a></td>
                        <?php } else { ?>
                            <td><i class="fa fa-times" aria-hidden="true" style="color: red"></i></td>
                            <td><a href="<?php echo $this->url(array("controller" => "Festa", "action" => "acceptar", "id" => $festa['id'], "estat" => "1")); ?>">Acceptar inivitacio</a></td>
                        <?php } ?>
                    </tr>

                    <?php
                }
                ?>

            </table>

        </div>

    </div>

</div>